const CREATE_EXPENSE = 'CREATE_EXPENSE';
const EDIT_EXPENSE = 'EDIT_EXPENSE';
const VIEW_EXPENSES = 'VIEW_EXPENSES';
const DELETE_EXPENSE = 'DELETE_EXPENSE';

export { CREATE_EXPENSE, EDIT_EXPENSE, VIEW_EXPENSES, DELETE_EXPENSE };
